### ISSUE TITLE
[Bug] Previous tagged versions documentation is not displayed on Doc page

### ISSUE THREAD

**Issue by DariusIMP** [eclipse-zenoh/zenoh-java#54]
### Describe the bug

Describe the bug
A dropdown menu should allow us to select older versions of the documentation. The Dokka framework allows to do so.

To reproduce
See https://eclipse-zenoh.github.io/zenoh-java/index.html and check that you cant select 0.10.0-rc version documentation.

System info
N/A

### To reproduce

N/A

### System info

N/A

**Comment by milyin** [comment]
Closing as too old. Anyway with new java API documentation will be reviewed
